version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bankcards_db
    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: bankcards_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankcards
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      ENCRYPTION_KEY: "aesEncryptionKey1234567890123456"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: